
-- Creating PRIMARY KEY constraints 

ALTER TABLE BOOTH
   ADD CONSTRAINT PK_BOOTH PRIMARY KEY (BOOTHCODE);

ALTER TABLE BILL
   ADD CONSTRAINT PK_BILL PRIMARY KEY (BILL_ID);


ALTER TABLE DESSERT
   ADD CONSTRAINT PK_DESSERT PRIMARY KEY (DESSERT_CODE);

ALTER TABLE OFFER
   ADD CONSTRAINT PK_OFFER PRIMARY KEY (DESSERT_CODE, DESSERT_OFFERED_DATE_RANGE, RESTAURANT_ID);

ALTER TABLE RESTAURANT
   ADD CONSTRAINT PK_RESTAURANT PRIMARY KEY (RESTAURANT_ID);
 
 
   
-- Creating FOREIGN KEY constraints 

ALTER TABLE BILL
   ADD CONSTRAINT FK_BILL_CONTAIN_DESSERT FOREIGN KEY (DESSERT_CODE)
      REFERENCES DESSERT (DESSERT_CODE);

ALTER TABLE BILL
   ADD CONSTRAINT FK_CHECK_GENERATES_BOOTH FOREIGN KEY (BOOTHCODE)
      REFERENCES BOOTH (BOOTHCODE);

ALTER TABLE BILL
   ADD CONSTRAINT FK_CHECK_PROCESS_RESTAURA FOREIGN KEY (RESTAURANT_ID)
      REFERENCES RESTAURANT (RESTAURANT_ID);

ALTER TABLE OFFER
   ADD CONSTRAINT FK_OFFER_DESSERT FOREIGN KEY (DESSERT_CODE)
      REFERENCES DESSERT (DESSERT_CODE);

ALTER TABLE OFFER
   ADD CONSTRAINT FK_OFFER_RESTAURA FOREIGN KEY (RESTAURANT_ID)
      REFERENCES RESTAURANT (RESTAURANT_ID);



